# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b3e308ba450a31ba2a58186b65569dfe631ed86f54a1694a454084a14c73792c76a67dd28d2ad5139fa88baf58a22660a265115b89c5aa020370fe6a747fc318

test:
  secret_key_base: 980f41c49b3dd0e434ad2d147114645489380df928c87e356bf24bd3867994b4862223bfed19f834a2dd00b951d8a19dcb89d12bd199ebe3caf300e8a4d71362

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
